import { describe, expect, it } from "vitest";

import {
  INSTANCE_ID_PATTERN,
  InvalidKey,
  base32,
  generateInstanceId,
  generateSecret,
  mint,
  normaliseInstanceId,
  verify,
} from "../src/keys.ts";

const SECRET = "secret-one";
const OTHER_SECRET = "secret-two";

describe("compatibility with the Python relay", () => {
  // Generated by legacy-python/src/canopy_apns/keys.py. If any of these stop
  // matching, every key already issued stops working.
  const vectors: [string, string, string][] = [
    ["acme", "secret-one", "canopy_acme_g5xohf7fgty43bp6ynws2vjruu"],
    ["notcanopy", "test-signing-secret", "canopy_notcanopy_uqqyz5jyiiktm4ks4jtxmqkccm"],
    [
      "tpg6b7n6uwtjiaqzmerq",
      "HpQ2rXn7YtKf3vLcB8mZsW1dJgN6uE0aTiOxV5kRlPyC4hbQzSjMwFnA9eDgUt",
      "canopy_tpg6b7n6uwtjiaqzmerq_lyxh2sd63xenlw2h3tpfbqvjmy",
    ],
    ["a", "x", "canopy_a_dr4mmpoqnogr2sb2vw52sloejm"],
  ];

  it.each(vectors)("mints %s the same way", async (id, secret, expected) => {
    expect(await mint(id, secret)).toBe(expected);
  });

  it.each(vectors)("verifies a Python-issued key for %s", async (id, secret, key) => {
    expect((await verify(key, secret)).id).toBe(id);
  });

  it("encodes base32 the way Python's b32encode does, lowercased and unpadded", () => {
    expect(base32(Uint8Array.from({ length: 11 }, (_, i) => i + 1))).toBe("aebagbafaydqqcikbm");
    expect(base32(Uint8Array.from({ length: 12 }, (_, i) => i + 1))).toBe("aebagbafaydqqcikbmga");
  });
});

it("mint is deterministic, so a lost key can be handed out again", async () => {
  expect(await mint("acme", SECRET)).toBe(await mint("acme", SECRET));
});

it("mint embeds the instance id", async () => {
  const key = await mint("acme", SECRET);
  expect(key.startsWith("canopy_acme_")).toBe(true);
  expect((await verify(key, SECRET)).id).toBe("acme");
});

it("normalises ids before signing, so case and whitespace do not make a second key", async () => {
  expect(await mint("  ACME  ", SECRET)).toBe(await mint("acme", SECRET));
});

it.each(["", "  ", "has_underscore", "-leading", "trailing-", "Uppercase!", "a".repeat(64)])(
  "refuses the unusable id %j at mint time",
  (bad) => {
    expect(() => normaliseInstanceId(bad)).toThrow();
  },
);

it("does not verify a key from another secret — rotation is the break-glass revocation", async () => {
  const key = await mint("acme", OTHER_SECRET);
  await expect(verify(key, SECRET)).rejects.toBeInstanceOf(InvalidKey);
});

it("does not verify a tampered instance id; the signature is what has to hold", async () => {
  const signature = (await mint("acme", SECRET)).split("_")[2];
  await expect(verify(`canopy_victim_${signature}`, SECRET)).rejects.toBeInstanceOf(InvalidKey);
});

it.each([
  "",
  "not-a-key",
  "canopy_acme",
  "canopy_acme_sig_extra",
  "wrongprefix_acme_sig",
  "canopy_has_underscore",
])("refuses the malformed key %j", async (bad) => {
  await expect(verify(bad, SECRET)).rejects.toBeInstanceOf(InvalidKey);
});

it("generates distinct, long secrets", () => {
  const first = generateSecret();
  expect(first).not.toBe(generateSecret());
  expect(first).toHaveLength(64);
  expect(first).toMatch(/^[A-Za-z0-9_-]+$/);
});

it("generates enrollment ids that are usable and distinct", async () => {
  const ids = new Set(Array.from({ length: 200 }, generateInstanceId));
  expect(ids.size).toBe(200);
  for (const id of ids) {
    expect(id).toMatch(INSTANCE_ID_PATTERN);
    expect((await verify(await mint(id, SECRET), SECRET)).id).toBe(id);
  }
});
