/**
 * Instance API keys, derived rather than stored.
 *
 * An API key here is not a random string looked up in a table — there is no
 * table.  It is an instance id with a MAC over it:
 *
 *     canopy_<instance-id>_<signature>
 *
 * The relay verifies a key by recomputing the signature from
 * `CANOPY_APNS_SIGNING_SECRET` and comparing.  That is what lets the service
 * be stateless: no database, and no two isolates that can disagree about who
 * is allowed in.
 *
 * **Byte-compatible with the Python relay** (`legacy-python/`).  Same HMAC,
 * same truncation, same base32 alphabet, so every key the Python service ever
 * issued verifies here unchanged, given the same signing secret.  The tests
 * pin that with vectors generated by the Python code.
 *
 * * **Issuing a key writes nothing.**  Enrollment invents a random id and
 *   derives its key; there is no allocation to record.
 * * **The instance id is legible in the key.**  Deliberate: logs and
 *   rate-limit buckets are keyed on it.  It is an identifier, not a secret.
 * * **Revocation is a list, not a delete.**  `CANOPY_APNS_REVOKED_INSTANCES`
 *   for one instance, rotating the signing secret for all of them.
 *
 * No Workers-only APIs in this module: `scripts/cli.ts` runs it under Node to
 * mint keys and secrets locally.
 */

export const KEY_PREFIX = "canopy";

/** Lowercase alphanumerics and internal hyphens.  No underscore — that is the
 * field separator — and no leading or trailing hyphen. */
export const INSTANCE_ID_PATTERN = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

/** 16 bytes of HMAC-SHA256 output.  128 bits is far past forging range for a
 * value an attacker can only test online against a rate-limited endpoint. */
export const SIGNATURE_BYTES = 16;

/** Bytes of randomness behind a self-enrolled instance id.  About collision
 * avoidance rather than secrecy: the id is not the secret half of a key. */
export const INSTANCE_ID_BYTES = 12;

/**
 * The presented key is not one this relay issued.
 *
 * Carries no detail about *why* on purpose — the caller gets one flat
 * rejection, so a probing client learns nothing.
 */
export class InvalidKey extends Error {}

export interface Instance {
  id: string;
}

const BASE32_ALPHABET = "abcdefghijklmnopqrstuvwxyz234567";

/**
 * Base32, lowercased, unpadded — Python's `b32encode(...).rstrip("=").lower()`.
 *
 * Base64url would be shorter, but its alphabet includes `_`, which is the
 * field separator.
 */
export function base32(bytes: Uint8Array): string {
  let out = "";
  let buffer = 0;
  let bits = 0;
  for (const byte of bytes) {
    buffer = (buffer << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      out += BASE32_ALPHABET[(buffer >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) {
    out += BASE32_ALPHABET[(buffer << (5 - bits)) & 31];
  }
  return out;
}

/** Lowercase and trim an id, or throw if unusable.  Applied at mint time so a
 * key can never be issued for an id that `verify` would refuse to parse. */
export function normaliseInstanceId(instanceId: string): string {
  const candidate = instanceId.trim().toLowerCase();
  if (!INSTANCE_ID_PATTERN.test(candidate)) {
    throw new Error(
      "An instance id is 1-63 characters of lowercase letters, digits and " +
        "internal hyphens — no underscores, since that separates the parts " +
        `of a key. Got ${JSON.stringify(instanceId)}.`,
    );
  }
  return candidate;
}

const encoder = new TextEncoder();
const hmacKeys = new Map<string, Promise<CryptoKey>>();

function hmacKey(secret: string): Promise<CryptoKey> {
  let key = hmacKeys.get(secret);
  if (key === undefined) {
    key = crypto.subtle.importKey(
      "raw",
      encoder.encode(secret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"],
    );
    hmacKeys.set(secret, key);
  }
  return key;
}

/** The signature half of `instanceId`'s key. */
export async function sign(instanceId: string, secret: string): Promise<string> {
  const mac = await crypto.subtle.sign("HMAC", await hmacKey(secret), encoder.encode(instanceId));
  return base32(new Uint8Array(mac).slice(0, SIGNATURE_BYTES));
}

/** The API key for `instanceId`.  Deterministic: same id, same key, so a lost
 * key can be handed out again without anything having to remember it. */
export async function mint(instanceId: string, secret: string): Promise<string> {
  const normalised = normaliseInstanceId(instanceId);
  return `${KEY_PREFIX}_${normalised}_${await sign(normalised, secret)}`;
}

/** Constant-time string comparison; the comparison is the only thing standing
 * between a guessed signature and a valid one. */
function constantTimeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

/**
 * Authenticate `apiKey`, returning who it belongs to.
 *
 * Throws `InvalidKey` for anything that is not a well-formed key carrying a
 * correct signature.  Revocation is not checked here — that is the caller's
 * business, so this stays a pure function of the key and the secret.
 */
export async function verify(apiKey: string, secret: string): Promise<Instance> {
  const parts = (apiKey ?? "").trim().split("_");
  if (parts.length !== 3) throw new InvalidKey("malformed key");

  const [prefix, instanceId, signature] = parts as [string, string, string];
  if (prefix !== KEY_PREFIX || !INSTANCE_ID_PATTERN.test(instanceId)) {
    throw new InvalidKey("malformed key");
  }

  if (!constantTimeEqual(signature, await sign(instanceId, secret))) {
    throw new InvalidKey("bad signature");
  }
  return { id: instanceId };
}

function base64url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

/** A fresh signing secret, for `npm run secret`.  Same shape as Python's
 * `secrets.token_urlsafe(48)`: 64 URL-safe base64 characters. */
export function generateSecret(): string {
  return base64url(crypto.getRandomValues(new Uint8Array(48)));
}

/** A fresh random instance id, for self-service enrollment.  Base32 keeps it
 * inside `INSTANCE_ID_PATTERN` with no separator characters. */
export function generateInstanceId(): string {
  return base32(crypto.getRandomValues(new Uint8Array(INSTANCE_ID_BYTES)));
}
